export const START_FETCHING_RECIPES = "START_FETCHING_RECIPES";
export const STOP_FETCHING_RECIPES = "STOP_FETCHING_RECIPES";
export const SET_RECIPES = "SET_RECIPES";
export const SET_RECIPE = "SET_RECIPE";
export const SET_SPECIALS = "SET_SPECIALS";
